env:
  global:
    - CC_TEST_REPORTER_ID=191c0893508b7704fa2415884f476a76e18b456c36b7f66efa624f5819e622a2

language: node_js
node_js:
  - 'stable'
before_install:
  - 'nvm install-latest-npm'

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script:
  - npm run test -- --coverage --no-cache

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT

after_success:
  - COVERALLS_REPO_TOKEN=$coveralls_repo_token npm run coveralls

